 
export const OscarMovies=  [
  {
    adult: false,
    backdrop_path: '/bYimqNnizPUCnL5HOdoCW02IGmH.jpg',
    genre_ids: [Array],
    id: 74643,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'The Artist',
    overview: 'Hollywood, 1927: As silent movie star George Valentin wonders if the arrival of talking pictures will cause him to fade into oblivion, he sparks with Peppy Miller, a young dancer set for a big break.',        
    popularity: 9.495,
    poster_path: '/khtVL4abxYczXAWbo1wAz13CLx3.jpg',
    release_date: '2011-10-08',
    title: 'The Artist',
    video: false,
    vote_average: 7.4,
    vote_count: 2397
  },
  {
    adult: false,
    backdrop_path: '/briUEoIqNxvo9Q7tsDI7hzCf6GG.jpg',
    genre_ids: [Array],
    id: 65057,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'The Descendants',
    overview: 'With his wife Elizabeth on life support after a boating accident, Hawaiian land baron, Matt King takes his daughters on a trip from Oahu to Kauai to confront a young real estate broker, who was having an affair with Elizabeth before her misfortune.',
    popularity: 12.864,
    poster_path: '/mCpYsKQNOtaBYJWCRYYuFmLsB6X.jpg',
    release_date: '2011-09-09',
    title: 'The Descendants',
    video: false,
    vote_average: 6.8,
    vote_count: 2013
  },
  {
    adult: false,
    backdrop_path: '/hTc55dlCPMP4oqrUU66GjKjSblp.jpg',
    genre_ids: [Array],
    id: 64685,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Extremely Loud & Incredibly Close',
    overview: "A year after his father's death, Oskar, a troubled young boy, discovers a mysterious key he believes was left for him by his father and embarks on a scavenger hunt to find the matching lock.",
    popularity: 12.94,
    poster_path: '/6pszViNvKr1r31pP7gJNYDHEx5P.jpg',
    release_date: '2011-12-24',
    title: 'Extremely Loud & Incredibly Close',
    video: false,
    vote_average: 7,
    vote_count: 1586
  },
  {
    adult: false,
    backdrop_path: '/yDwL5qAHeSyaozgXXcYnAOp4AUF.jpg',
    genre_ids: [Array],
    id: 50014,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'The Help',
    overview: `Aibileen Clark is a middle-aged African-American maid who has spent her life raising white children and has recently lost her only son; Minny Jackson is an African-American maid who has often offended her employers despite her family's struggles with money and her desperate need for jobs; and Eugenia "Skeeter" Phelan is 
a young white woman who has recently moved back home after graduating college to find out her childhood maid has 
mysteriously disappeared. These three stories intertwine to explain how life in Jackson, Mississippi revolves around "the help"; yet they are always kept at a certain distance because of racial lines.`,
    popularity: 21.228,
    poster_path: '/7XLSwxpfpPoJyTdJVot6a42TS2V.jpg',
    release_date: '2011-08-09',
    title: 'The Help',
    video: false,
    vote_average: 8.2,
    vote_count: 5484
  },
  {
    adult: false,
    backdrop_path: '/jlh5bNiSPcbQ79Nt31kE2GxIR3h.jpg',
    genre_ids: [Array],
    id: 44826,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Hugo',
    overview: "Orphaned and alone except for an uncle, Hugo Cabret lives in the walls of a train station in 1930s Paris. Hugo's job is to oil and maintain the station's clocks, but to him, his more important task is to protect a broken automaton and notebook left to him by his late father. Accompanied by the goddaughter of an embittered toy merchant, Hugo embarks on a quest to solve the mystery of the automaton and find a place he can call home.",
    popularity: 21.718,
    poster_path: '/vDAhBTIHvIoNOlgCfmLirVgUK2p.jpg',
    release_date: '2011-11-22',
    title: 'Hugo',
    video: false,
    vote_average: 7.2,
    vote_count: 5525
  },
  {
    adult: false,
    backdrop_path: '/b5bcKhvN6VP82U5ztNdPfOLiolD.jpg',
    genre_ids: [Array],
    id: 59436,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Midnight in Paris',
    overview: 'A romantic comedy about a family traveling to the French capital for business. The party includes a young engaged couple forced to confront the illusion that a life different from their own is better.',       
    popularity: 16.151,
    poster_path: '/4wBG5kbfagTQclETblPRRGihk0I.jpg',
    release_date: '2011-05-11',
    title: 'Midnight in Paris',
    video: false,
    vote_average: 7.5,
    vote_count: 5576
  },
  {
    adult: false,
    backdrop_path: '/qbWrn6xaWK4nkzMRfP6oBBUW2cy.jpg',
    genre_ids: [Array],
    id: 60308,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Moneyball',
    overview: "The story of Oakland Athletics general manager Billy Beane's successful attempt to put together a baseball team on a budget, by employing computer-generated analysis to draft his players.",
    popularity: 18.85,
    poster_path: '/4yIQq1e6iOcaZ5rLDG3lZBP3j7a.jpg',
    release_date: '2011-09-22',
    title: 'Moneyball',
    video: false,
    vote_average: 7.2,
    vote_count: 3427
  },
  {
    adult: false,
    backdrop_path: '/iXpmOZJwvYXieyie7U5qJfc0m3s.jpg',
    genre_ids: [Array],
    id: 8967,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'The Tree of Life',
    overview: 'The impressionistic story of a Texas family in the 1950s. The film follows the life journey of the eldest son, Jack, through the innocence of childhood to his disillusioned adult years as he tries to reconcile a complicated relationship with his father. Jack finds himself a lost soul in the modern world, seeking answers to the origins and meaning of life while questioning the existence of faith.',
    popularity: 13.32,
    poster_path: '/l8cwuB5WJSoj4uMAsnzuHBOMaSJ.jpg',
    release_date: '2011-05-17',
    title: 'The Tree of Life',
    video: false,
    vote_average: 6.7,
    vote_count: 2307
  },
  {
    adult: false,
    backdrop_path: '/64YOcrslrijllDRCpQvXkSKvXQV.jpg',
    genre_ids: [Array],
    id: 57212,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'War Horse',
    overview: 'Follows a young man named Albert and his horse, Joey, and how their bond is broken when Joey is sold to the cavalry and sent to the trenches of World War One. Despite being too young to enlist, Albert heads to France to save his friend.',
    popularity: 21.219,
    poster_path: '/7KHz6JlJhrFAPesmUkgdnLrSr8Y.jpg',
    release_date: '2011-12-25',
    title: 'War Horse',
    video: false,
    vote_average: 7.3,
    vote_count: 2534
  }
]
 
 
 const movies=[
    {
      adult: false,
      backdrop_path: '/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg',
      genre_ids: [Array],
      id: 284053,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Thor: Ragnarok',
      overview: 'Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.',
      popularity: 152.85,
      poster_path: '/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg',
      release_date: '2017-10-25',
      title: 'Thor: Ragnarok',
      video: false,
      vote_average: 7.6,
      vote_count: 15565
    },
    {
      adult: false,
      backdrop_path: '/vMNEvp4wKAkDIODZjz5BsqVWY9y.jpg',
      genre_ids: [Array],
      id: 315635,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Spider-Man: Homecoming',
      overview: 'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
      popularity: 142.341,
      poster_path: '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
      release_date: '2017-07-05',
      title: 'Spider-Man: Homecoming',
      video: false,
      vote_average: 7.4,
      vote_count: 15827
    },
    {
      adult: false,
      backdrop_path: '/aJn9XeesqsrSLKcHfHP4u5985hn.jpg',
      genre_ids: [Array],
      id: 283995,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Guardians of the Galaxy Vol. 2',
      overview: "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
      popularity: 100.266,
      poster_path: '/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg',
      release_date: '2017-04-19',
      title: 'Guardians of the Galaxy Vol. 2',
      video: false,
      vote_average: 7.6,
      vote_count: 16274
    },
    {
      adult: false,
      backdrop_path: '/yEv8c6i79vk06sZDC3Z9D8HQLVV.jpg',
      genre_ids: [Array],
      id: 263115,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Logan',
      overview: "In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",        
      popularity: 87.907,
      poster_path: '/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg',
      release_date: '2017-02-28',
      title: 'Logan',
      video: false,
      vote_average: 7.8,
      vote_count: 15452
    },
    {
      adult: false,
      backdrop_path: '/aL53oMdZKZRJRH8txH07DLuleF9.jpg',
      genre_ids: [Array],
      id: 284052,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Doctor Strange',
      overview: 'After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.',
      popularity: 197.923,
      poster_path: '/xf8PbyQcR5ucXErmZNzdKR0s8ya.jpg',
      release_date: '2016-10-25',
      title: 'Doctor Strange',
      video: false,
      vote_average: 7.4,
      vote_count: 16632
    },
    {
      adult: false,
      backdrop_path: '/2ex2beZ4ssMeOduLD0ILzXKCiep.jpg',
      genre_ids: [Array],
      id: 246655,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'X-Men: Apocalypse',
      overview: "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
      popularity: 80.239,
      poster_path: '/2mtQwJKVKQrZgTz49Dizb25eOQQ.jpg',
      release_date: '2016-05-18',
      title: 'X-Men: Apocalypse',
      video: false,
      vote_average: 6.5,
      vote_count: 10303
    },
    {
      adult: false,
      backdrop_path: '/kvRT3GwcnqGHzPjXIVrVPhUix7Z.jpg',
      genre_ids: [Array],
      id: 271110,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Captain America: Civil War',
      overview: 'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
      popularity: 120.668,
      poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
      release_date: '2016-04-27',
      title: 'Captain America: Civil War',
      video: false,
      vote_average: 7.4,
      vote_count: 17703
    },
    {
      adult: false,
      backdrop_path: '/en971MEXui9diirXlogOrPKmsEn.jpg',
      genre_ids: [Array],
      id: 293660,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Deadpool',
      overview: 'Deadpool tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.',
      popularity: 118.216,
      poster_path: '/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg',
      release_date: '2016-02-09',
      title: 'Deadpool',
      video: false,
      vote_average: 7.6,
      vote_count: 24597
    },
    {
      adult: false,
      backdrop_path: '/gzhVcfC5j0sTnS4WJzBrCS0Vkr0.jpg',
      genre_ids: [Array],
      id: 166424,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Fantastic Four',
      overview: 'Four young outsiders teleport to a dangerous universe, which alters their physical form in shocking ways. Their lives irrevocably upended, the team must learn to harness their daunting new abilities and work together to save Earth from a former friend turned enemy.',
      popularity: 44.406,
      poster_path: '/oeMpEsjmiT9PEJbRM1Fm7TZ1dE0.jpg',
      release_date: '2015-08-05',
      title: 'Fantastic Four',
      video: false,
      vote_average: 4.4,
      vote_count: 4687
    },
    {
      adult: false,
      backdrop_path: '/7AyEEZVtFjNMCOEoz88pBqiAI8n.jpg',
      genre_ids: [Array],
      id: 102899,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Ant-Man',
      overview: 'Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that save the world.',
      popularity: 89.811,
      poster_path: '/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg',
      release_date: '2015-07-14',
      title: 'Ant-Man',
      video: false,
      vote_average: 7.1,
      vote_count: 15251
    },
    {
      adult: false,
      backdrop_path: '/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg',
      genre_ids: [Array],
      id: 99861,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Avengers: Age of Ultron',
      overview: 'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
      popularity: 142.596,
      poster_path: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
      release_date: '2015-04-22',
      title: 'Avengers: Age of Ultron',
      video: false,
      vote_average: 7.3,
      vote_count: 17543
    },
    {
      adult: false,
      backdrop_path: '/mZSAu5acXueGC4Z3S5iLSWx8AEp.jpg',
      genre_ids: [Array],
      id: 118340,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Guardians of the Galaxy',
      overview: 'Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.',
      popularity: 40.831,
      poster_path: '/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
      release_date: '2014-07-30',
      title: 'Guardians of the Galaxy',
      video: false,
      vote_average: 7.9,
      vote_count: 22165
    },
    {
      adult: false,
      backdrop_path: '/hUPgIibqZlwbhs4N08cPzzc4f5K.jpg',
      genre_ids: [Array],
      id: 127585,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'X-Men: Days of Future Past',
      overview: 'The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.',
      popularity: 63.442,
      poster_path: '/bvN8iUpHyBIvniUk4e52SUZMA7Z.jpg',
      release_date: '2014-05-15',
      title: 'X-Men: Days of Future Past',
      video: false,
      vote_average: 7.5,
      vote_count: 12260
    },
    {
      adult: false,
      backdrop_path: '/rF3kAqk08zGSvs8m6hRwsi28nHg.jpg',
      genre_ids: [Array],
      id: 102382,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'The Amazing Spider-Man 2',
      overview: 'For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.',
      popularity: 63.834,
      poster_path: '/h4NC0pkqvDX7Q6TI3PyW4NJKEYi.jpg',
      release_date: '2014-04-16',
      title: 'The Amazing Spider-Man 2',
      video: false,
      vote_average: 6.4,
      vote_count: 9166
    },
    {
      adult: false,
      backdrop_path: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
      genre_ids: [Array],
      id: 100402,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Captain America: The Winter Soldier',
      overview: 'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
      popularity: 69.942,
      poster_path: '/5r1zWuzbsVAYSPzvCecAReGhN7k.jpg',
      release_date: '2014-03-20',
      title: 'Captain America: The Winter Soldier',
      video: false,
      vote_average: 7.7,
      vote_count: 14205
    },
    {
      adult: false,
      backdrop_path: '/uhYoytlNaq46dG81wLmHqaSuzWu.jpg',
      genre_ids: [Array],
      id: 76338,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Thor: The Dark World',
      overview: 'Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.',
      popularity: 69.057,
      poster_path: '/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg',
      release_date: '2013-10-29',
      title: 'Thor: The Dark World',
      video: false,
      vote_average: 6.6,
      vote_count: 13157
    },
    {
      adult: false,
      backdrop_path: '/AqIes6H9NlRoo0YjlO7exLCu72v.jpg',
      genre_ids: [Array],
      id: 76170,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'The Wolverine',
      overview: 'Wolverine faces his ultimate nemesis - and tests of his physical, emotional, and mortal limits - in a life-changing voyage to modern-day Japan.',
      popularity: 7.534,
      poster_path: '/9zvDWFdc22pzq0BMcEsQaakBgPj.jpg',
      release_date: '2013-07-23',
      title: 'The Wolverine',
      video: false,
      vote_average: 6.4,
      vote_count: 7491
    },
    {
      adult: false,
      backdrop_path: '/wPgcxHNvnEEMXx94l2911gqZ4o9.jpg',
      genre_ids: [Array],
      id: 68721,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Iron Man 3',
      overview: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
      popularity: 77.686,
      poster_path: '/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
      release_date: '2013-04-18',
      title: 'Iron Man 3',
      video: false,
      vote_average: 6.9,
      vote_count: 17481
    },
    {
      adult: false,
      backdrop_path: '/eaJwlzDiMC5k4kp766NO8yXnt7U.jpg',
      genre_ids: [Array],
      id: 1930,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'The Amazing Spider-Man',
      overview: "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
      popularity: 61.377,
      poster_path: '/dQ8TOCYgP9pzQvSb1cmaalYqdb5.jpg',
      release_date: '2012-06-23',
      title: 'The Amazing Spider-Man',
      video: false,
      vote_average: 6.6,
      vote_count: 12689
    },
    {
      adult: false,
      backdrop_path: '/nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg',
      genre_ids: [Array],
      id: 24428,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'The Avengers',
      overview: 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
      popularity: 152.31,
      poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
      release_date: '2012-04-25',
      title: 'The Avengers',
      video: false,
      vote_average: 7.7,
      vote_count: 24294
    },
    {
      adult: false,
      backdrop_path: '/mLBReXFauC7xtbvWOMaBM891vF7.jpg',
      genre_ids: [Array],
      id: 71676,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Ghost Rider: Spirit of Vengeance',
      overview: 'When the devil resurfaces with aims to take over the world in human form, Johnny Blaze reluctantly comes out of hiding to transform into the flame-spewing supernatural hero Ghost Rider -- and rescue a 10-year-old boy from an unsavory end.',
      popularity: 32.14,
      poster_path: '/fDtIZXLNreDHk3mOskJYABrQNOQ.jpg',
      release_date: '2011-12-11',
      title: 'Ghost Rider: Spirit of Vengeance',
      video: false,
      vote_average: 4.9,
      vote_count: 2716
    },
    {
      adult: false,
      backdrop_path: '/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg',
      genre_ids: [Array],
      id: 1771,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Captain America: The First Avenger',
      overview: "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
      popularity: 65.259,
      poster_path: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
      release_date: '2011-07-22',
      title: 'Captain America: The First Avenger',
      video: false,
      vote_average: 6.9,
      vote_count: 16449
    },
    {
      adult: false,
      backdrop_path: '/4Ky8OcB0F7x3PRZQIiFFZyf3eIX.jpg',
      genre_ids: [Array],
      id: 49538,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'X-Men: First Class',
      overview: 'Before Charles Xavier and Erik Lensherr took the names Professor X and Magneto, they were two young men discovering their powers for the first time. Before they were arch-enemies, they were closest of friends, working together with other mutants (some familiar, some new), to stop the greatest threat the world has ever known.',
      popularity: 2.205,
      poster_path: '/yoKdvhqVw45oEF34No2cD7aP3sx.jpg',
      release_date: '2011-06-01',
      title: 'X-Men: First Class',
      video: false,
      vote_average: 7.3,
      vote_count: 10055
    },
    {
      adult: false,
      backdrop_path: '/c5tewtijj6aixi8zwwPuYJxifBA.jpg',
      genre_ids: [Array],
      id: 10195,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Thor',
      overview: "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
      popularity: 73.645,
      poster_path: '/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
      release_date: '2011-04-21',
      title: 'Thor',
      video: false,
      vote_average: 6.8,
      vote_count: 16224
    },
    {
      adult: false,
      backdrop_path: '/jesRqfL9v6HNnowe795xjmuKUXl.jpg',
      genre_ids: [Array],
      id: 10138,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'Iron Man 2',
      overview: "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
      popularity: 78.461,
      poster_path: '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
      release_date: '2010-04-28',
      title: 'Iron Man 2',
      video: false,
      vote_average: 6.8,
      vote_count: 15838
    },
    {
      adult: false,
      backdrop_path: '/wvqdJLVh0mSblly7UnYFPEk04Wd.jpg',
      genre_ids: [Array],
      id: 2080,
      media_type: 'movie',
      original_language: 'en',
      original_title: 'X-Men Origins: Wolverine',
      overview: 'After seeking to live a normal life, Logan sets out to avenge the death of his girlfriend by undergoing the mutant Weapon X program and becoming Wolverine.',
      popularity: 4.159,
      poster_path: '/mQglrQzgZT0Oj9cQYPsLI8dsEqB.jpg',
      release_date: '2009-04-28',
      title: 'X-Men Origins: Wolverine',
      video: false,
      vote_average: 6.2,
      vote_count: 8102
    },
]
export const DCMovies=[
  {
    adult: false,
    backdrop_path: '/egg7KFi18TSQc1s24RMmR9i2zO6.jpg',
    genre_ids: [Array],
    id: 464052,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Wonder Woman 1984',
    overview: 'A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.',
    popularity: 1693.774,
    poster_path: '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
    release_date: '2020-12-16',
    title: 'Wonder Woman 1984',
    video: false,
    vote_average: 6.8,
    vote_count: 4442
  },
  {
    adult: false,
    backdrop_path: '/qwgGtdlLMKYvT2tV8hLY22syRHN.jpg',
    genre_ids: [Array],
    id: 287947,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Shazam!',
    overview: 'A boy is given the ability to become an adult superhero in times of need with a single magic word.',
    popularity: 235.048,
    poster_path: '/xnopI5Xtky18MPhK40cZAGAOVeV.jpg',
    release_date: '2019-03-29',
    title: 'Shazam!',
    video: false,
    vote_average: 7.1,
    vote_count: 6257
  },
  {
    adult: false,
    backdrop_path: '/9QusGjxcYvfPD1THg6oW3RLeNn7.jpg',
    genre_ids: [Array],
    id: 297802,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Aquaman',
    overview: "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.",
    popularity: 145.938,
    poster_path: '/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg',
    release_date: '2018-12-07',
    title: 'Aquaman',
    video: false,
    vote_average: 6.9,
    vote_count: 10208
  },
  {
    adult: false,
    backdrop_path: '/jorgjEk6a0bed6jdR5wu4S6ZvRm.jpg',
    genre_ids: [Array],
    id: 141052,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Justice League',
    overview: "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
    popularity: 316.235,
    poster_path: '/eifGNCSDuxJeS1loAXil5bIGgvC.jpg',
    release_date: '2017-11-15',
    title: 'Justice League',
    video: false,
    vote_average: 6.2,
    vote_count: 10330
  },
  {
    adult: false,
    backdrop_path: '/AaABt75ZzfMGrscUR2seabz4PEX.jpg',
    genre_ids: [Array],
    id: 297762,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Wonder Woman',
    overview: 'An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict.',
    popularity: 114.421,
    poster_path: '/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg',
    release_date: '2017-05-30',
    title: 'Wonder Woman',
    video: false,
    vote_average: 7.3,
    vote_count: 16194
  },
  {
    adult: false,
    backdrop_path: '/1Nn2aBWB1x91GmvFm9F5SM2nQl3.jpg',
    genre_ids: [Array],
    id: 297761,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Suicide Squad',
    overview: 'From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences.',
    popularity: 54.457,
    poster_path: '/xFw9RXKZDvevAGocgBK0zteto4U.jpg',
    release_date: '2016-08-03',
    title: 'Suicide Squad',
    video: false,
    vote_average: 5.9,
    vote_count: 17139
  },
  {
    adult: false,
    backdrop_path: '/mX3WOJPBzzl4kj4xU5lL7qfD6C3.jpg',
    genre_ids: [Array],
    id: 209112,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Batman v Superman: Dawn of Justice',
    overview: 'Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.',
    popularity: 169.61,
    poster_path: '/5UsK3grJvtQrtzEgqNlDljJW96w.jpg',
    release_date: '2016-03-23',
    title: 'Batman v Superman: Dawn of Justice',
    video: false,
    vote_average: 5.9,
    vote_count: 14500
  },
  {
    adult: false,
    backdrop_path: '/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg',
    genre_ids: [Array],
    id: 49521,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Man of Steel',
    overview: 'A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.',
    popularity: 82.468,
    poster_path: '/4qgXzVAYNihFeudrys6WU4I01Q7.jpg',
    release_date: '2013-06-12',
    title: 'Man of Steel',
    video: false,
    vote_average: 6.6,
    vote_count: 11921
  },
  {
    adult: false,
    backdrop_path: '/cKPfiu9IcCW0fMdKdQBXe3PRtTZ.jpg',
    genre_ids: [Array],
    id: 49026,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'The Dark Knight Rises',
    overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
    popularity: 55.842,
    poster_path: '/vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg',
    release_date: '2012-07-16',
    title: 'The Dark Knight Rises',
    video: false,
    vote_average: 7.7,
    vote_count: 17540
  },
  {
    adult: false,
    backdrop_path: '/8EZ3hY4zhSorcRt4WtoaydsG3Ts.jpg',
    genre_ids: [Array],
    id: 44912,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Green Lantern',
    overview: 'For centuries, a small but powerful force of warriors called the Green Lantern Corps has sworn to keep intergalactic order. Each Green Lantern wears a ring that grants him superpowers. But when a new enemy called Parallax threatens to destroy the balance of power in the Universe, their fate and the fate of Earth lie in the hands of the first human ever recruited.',
    popularity: 44.683,
    poster_path: '/fj21HwUprqjjwTdkKC1XZurRSpV.jpg',
    release_date: '2011-06-16',
    title: 'Green Lantern',
    video: false,
    vote_average: 5.2,
    vote_count: 5563
  },
  {
    adult: false,
    backdrop_path: '/iNYe0BmPDAEQlChNYOfceGPNnq6.jpg',
    genre_ids: [Array],
    id: 20533,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Jonah Hex',
    overview: 'Gunslinger Jonah Hex is appointed by President Ulysses Grant to track down terrorist Quentin Turnbull, a former Confederate officer determined on unleashing hell on earth. Jonah not only secures freedom by accepting this task, he also gets revenge on the man who slayed his wife and child.',  
    popularity: 20.653,
    poster_path: '/1MpWjcCn8M0763QDoxcN0gXrc5q.jpg',
    release_date: '2010-06-18',
    title: 'Jonah Hex',
    video: false,
    vote_average: 4.7,
    vote_count: 961
  },
  {
    adult: false,
    backdrop_path: '/dH7ia3vtkYCa3CBvDnvVjqm9uiQ.jpg',
    genre_ids: [Array],
    id: 13183,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Watchmen',
    overview: 'In a gritty and alternate 1985 the glory days of costumed vigilantes have been brought to a close by a government crackdown, but after one of the masked veterans is brutally murdered, an investigation into the killer is initiated. The reunited heroes set out to prevent their own destruction, but in doing so uncover a sinister plot that puts all of humanity in grave danger.',
    popularity: 45.26,
    poster_path: '/aZvOkdo203bm1kpcY0A0Tn074ER.jpg',
    release_date: '2009-03-05',
    title: 'Watchmen',
    video: false,
    vote_average: 7.3,
    vote_count: 6695
  },
  {
    adult: false,
    backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    genre_ids: [Array],
    id: 155,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    popularity: 72.564,
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    release_date: '2008-07-16',
    title: 'The Dark Knight',
    video: false,
    vote_average: 8.5,
    vote_count: 24714
  },
  {
    adult: false,
    backdrop_path: '/8eRscFbRYl681zDfkjv1jjW1KAA.jpg',
    genre_ids: [Array],
    id: 1452,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Superman Returns',
    overview: 'Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest to felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel.',
    popularity: 27.71,
    poster_path: '/qIegbn6DSUYmggfwxOBNOVS35q.jpg',
    release_date: '2006-06-28',
    title: 'Superman Returns',
    video: false,
    vote_average: 5.6,
    vote_count: 3057
  },
  {
    adult: false,
    backdrop_path: '/lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg',
    genre_ids: [Array],
    id: 272,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Batman Begins',
    overview: 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.',
    popularity: 59.352,
    poster_path: '/1P3ZyEq02wcTMd3iE4ebtLvncvH.jpg',
    release_date: '2005-06-10',
    title: 'Batman Begins',
    video: false,
    vote_average: 7.7,
    vote_count: 15860
  },
  {
    adult: false,
    backdrop_path: '/x7fK0oOUX8Ks1B1lZsACmCXUybI.jpg',
    genre_ids: [Array],
    id: 314,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Catwoman',
    overview: `Liquidated after discovering a corporate conspiracy, mild-mannered graphic artist Patience Phillips washes up on an island, where she's resurrected and endowed with the prowess of a cat -- and she's eager to use her new skills ... as a vigilante. Before you can say "cat and mouse," handsome gumshoe Tom Lone is on her tail.`,
    popularity: 17.606,
    poster_path: '/pvnPgukFyEKgCzyOxyLiwyZ8T1C.jpg',
    release_date: '2004-07-22',
    title: 'Catwoman',
    video: false,
    vote_average: 4.6,
    vote_count: 2458
  },
  {
    adult: false,
    backdrop_path: '/61Wj1C1hrOyu6mAHARS8J5ShOzq.jpg',
    genre_ids: [Array],
    id: 8854,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Steel',
    overview: `Justice. Safe streets. Payback. Metallurgist John Henry Irons (O'Neal) vows to claim them all when a renegade military reject (Judd Nelson) puts new superweapons in dangerous hands. Helped by an electronics wiz (Annabeth Gish) and an imaginative scrap metal worker (Richard Roundtree), Irons becomes Steel. Wearing body armor, wielding a fearsome electrohammer and riding a gadget-packed motorcycle, he's ready to wage war...if he can fix the untimely glitches in his untested gear. "You all be cool now," the good-guy hero tells two crime victims he rescues. There'll be a lot of thrillin' before Steel himself can start chillin.'`,
    popularity: 10.222,
    poster_path: '/hbH8oXJZPwcYxaa1JrUMq4ogg7G.jpg',
    release_date: '1997-08-15',
    title: 'Steel',
    video: false,
    vote_average: 4.4,
    vote_count: 161
  },
  {
    adult: false,
    backdrop_path: '/rpOqHZMNIaI4qP4r7nw1B7oA0mx.jpg',
    genre_ids: [Array],
    id: 415,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Batman & Robin',
    overview: 'Batman and Robin deal with relationship issues while preventing Mr. Freeze and Poison Ivy from attacking Gotham City.',
    popularity: 25.498,
    poster_path: '/bsg0mrxUKyJoL4oSGP5mlhEsqp.jpg',
    release_date: '1997-06-20',
    title: 'Batman & Robin',
    video: false,
    vote_average: 4.3,
    vote_count: 3622
  },
  {
    adult: false,
    backdrop_path: '/snlu32RmjldF9b068UURJg8sQtn.jpg',
    genre_ids: [Array],
    id: 414,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Batman Forever',
    overview: 'Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat.',
    popularity: 22.898,
    poster_path: '/k6EQ2OewzjF8TcPgok9wxpPAgXW.jpg',
    release_date: '1995-06-16',
    title: 'Batman Forever',
    video: false,
    vote_average: 5.4,
    vote_count: 3741
  },
  {
    adult: false,
    backdrop_path: '/moYfd709S8xnb8Od2yeG5VBt9Bp.jpg',
    genre_ids: [Array],
    id: 364,
    media_type: 'movie',
    original_language: 'en',
    original_title: 'Batman Returns',
    overview: 'While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman.',  
    popularity: 29.712,
    poster_path: '/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg',
    release_date: '1992-06-19',
    title: 'Batman Returns',
    video: false,
    vote_average: 6.8,
    vote_count: 4513
  }
]
export default movies;